/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Reportes;

import controladores.ProductosJpaController;
import controladores.VentasJpaController;
import entidades.Productos;
import entidades.Ventas;
import java.awt.Image;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.Query;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Elliot
 */
public class RPVentasDiarias extends javax.swing.JFrame {
 VentasJpaController PVentas = new VentasJpaController();
  VentasJpaController cv=new VentasJpaController();
  EntityManager em=cv.getEntityManager();     
  DefaultTableModel dtm = new DefaultTableModel();
    /**
     * Creates new form RPVentasDiarias
     */
  
    
    public RPVentasDiarias() {
        initComponents();
        this.setLocationRelativeTo(null);
        obtenerf();
        llenar("");
        imprimir();
        calcTot();
        calcTotg();
        lblfecha.setVisible(false);
        lblfecha1.setVisible(false);
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/oki.png")).getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbventas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txttotven = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblfecha = new javax.swing.JLabel();
        lblfecha1 = new javax.swing.JLabel();
        porcentaje = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnexit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "COD.VENTA", "TIPO", "CLIENTE", "PRODUCTO", "TOTAL", "FECHA", "HORA"
            }
        ));
        jScrollPane1.setViewportView(tbventas);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("REPORTE DE VENTAS DIARIAS");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("PRODUCTO  :");

        txttotven.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("TOTAL_VENTA $");

        lblfecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblfecha.setText("f");

        lblfecha1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblfecha1.setText("FECHA :");

        porcentaje.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("PORCENTAJE OB.");

        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/exit_32x32_1.png"))); // NOI18N
        btnexit.setText("SALIR");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 197, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(155, 155, 155))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblfecha1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txttotven, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(porcentaje)))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnexit, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttotven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblfecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnexit, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void obtenerf(){ 
    Calendar c1 = Calendar.getInstance();
    Calendar c2 = new GregorianCalendar();
    String dia = Integer.toString(c2.get(Calendar.DATE));
    int mes = Integer.parseInt(Integer.toString(c2.get(Calendar.MONTH))) + 1;
    String annio = Integer.toString(c2.get(Calendar.YEAR));
    String mesr=String.valueOf(mes);
     if((Integer.parseInt(dia)<10)){
        dia="0"+Integer.toString(c2.get(Calendar.DATE));
     }if(mes<10){
        mesr="0"+String.valueOf(mes);
     } 
     
        lblfecha.setText(dia+"/"+mesr+"/"+annio);   
     
    
    }
    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        this.jTextField1.setText(jTextField1.getText().toUpperCase());
        llenar(jTextField1.getText());
        calcTot();
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
   this.setVisible(false);     // TODO add your handling code here:
    }//GEN-LAST:event_btnexitActionPerformed
    List<Object[]>lista=null;    
    private void llenar(String nomprod) {
          String sql="";
          try {
            if(nomprod.equals("")){
                sql="select idventa,"
                        + "(case when idtipov=1 then 'PUBLICO' else 'CLIENTE' end) as tipoventa,"
                        + "(case when v.idcliente>0 then (select nombre from cliente c where c.idcliente=v.idcliente)else 'XXXXXXXXXXXXXXXXXXXXXX' end)as nomcliente,"
                        + "(select nombre from productos pr where pr.idproducto=v.idproducto)as producto,"
                        + "total from ventas v where v.fechav='"+lblfecha.getText()+"'order by idventa";      
            }else{
                sql="select idventa,"
                        + "(case when idtipov=1 then 'PUBLICO' else 'CLIENTE' end) as tipoventa,"
                        + "(case when v.idcliente>0 then (select nombre from cliente c where c.idcliente=v.idcliente)else 'XXXXXXXXXXXXXXXXXXXXXX' end)as nomcliente,"
                        + "(select nombre from productos pr where pr.idproducto=v.idproducto)as producto,"
                        + "total from ventas v  HAVING producto like '%"+nomprod+"%' Order by idventa"; 
            }
                Query query=em.createNativeQuery(sql);
             lista=query.getResultList();
                String[] titulos = {"COD.VENTA","TIPO_VENTA","CLIENTE","PRODUCTO","TOTAL"};
                dtm=new DefaultTableModel(null,titulos);
                Object[]o=new Object[12];
            for(Object[] ok : lista){  
                   o[0]=ok[0];
                   o[1]=ok[1];
                   o[2]=ok[2];
                   o[3]=ok[3];
                   o[4]=ok[4];
                   dtm.addRow(o);
               }
                tbventas.setModel(dtm);
            } catch (Exception e) {
            }
    }
      public void calcTot() {
        double total = 0;double a;
        double b = 0;
        for (int i = 0; i < tbventas.getRowCount(); i++) {
            String Calculo = String.valueOf(tbventas.getValueAt(i, 4));
            a = Double.parseDouble(Calculo);
            b = b + a;
            if (i == tbventas.getRowCount() - 1) {
                txttotven.setText("" + b);
                total = b;
            }
        }
    }  
        public void calcTotg() {
        double total = 0;double a;
        double b = 0;
        
         for (int i = 0; i < tbventas.getRowCount(); i++) {
            int idpT=Integer.parseInt(String.valueOf(tbventas.getValueAt(i,0)));
            String sqlpad="select pr.padquicision from productos pr "
                    + "inner join ventas v using(idproducto) where fechav='"+lblfecha.getText()+"'";
            Query querys=em.createNativeQuery(sqlpad);
            List<Ventas> list=querys.getResultList();
            int ca=0;
            double pa=0.0;
            for(int x=0;x<list.size();x++){
             String sqlca="select carticulos from ventas where fechav='"+lblfecha.getText()+"'";
             Query querys1=em.createNativeQuery(sqlca);
             List<Ventas> lista=querys1.getResultList();
             ca=Integer.parseInt(String.valueOf(lista.get(i)));
             pa=Double.parseDouble(String.valueOf(list.get(i)));
             }
             //System.out.println("Vuelta:"+i+",Articulo:"+ca+",Pad:"+pa);
             String Calculo = String.valueOf(tbventas.getValueAt(i, 4));
             a = Double.parseDouble(Calculo)-(pa*ca);
             b =b+a;
             //System.out.println("Calculo:"+Calculo+"pad:"+(pa*ca));
            if (i == tbventas.getRowCount() - 1) {
                porcentaje.setText("" + b);
                total = b;
            }
          
            
        }
    }   
      
    public void imprimir(){
      /*  List listaa=new ArrayList();
        for(int i=0;i<tbventas.getRowCount();i++){
           List Ventas=new Ventas(tbventas.getValueAt(i,0),tbventas.getValueAt(i,0),tbventas.getValueAt(i,0),tbventas.getValueAt(i,0),tbventas.getValueAt(i,0),tbventas.getValueAt(i,0),tbventas.getValueAt(i,0),tbventas.getValueAt(i,0));
        }
        try {
            JasperReport reporte=(JasperReport) JRLoader.loadObject(lista).loadObjectFromFile("C:\\Users\\Elliot\\Documents\\SIVent\\src\\Reportes\\VentasDiarias.jasper");
            Map parametro=new HashMap();    
            parametro.put("idventa",lista.get(1).toString());
            JasperPrint jprint=JasperFillManager.fillReport(reporte,parametro,new JRBeanCollectionDataSource(lista));
            System.out.println("sdisdi");
            JasperViewer.viewReport(jprint);
        } catch (Exception e) {
        }*/
    }     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RPVentasDiarias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RPVentasDiarias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RPVentasDiarias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RPVentasDiarias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RPVentasDiarias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel lblfecha1;
    private javax.swing.JTextField porcentaje;
    private javax.swing.JTable tbventas;
    private javax.swing.JTextField txttotven;
    // End of variables declaration//GEN-END:variables
}
